import type { VercelRequest, VercelResponse } from "@vercel/node";
import {
  describeFlexError,
  mergePositions,
  parseSendRequest,
  parseStatement,
  toYahooTicker,
  type FlexError,
} from "./_ibkr-core.js";

// Fetches a user's real open positions from Interactive Brokers via the Flex
// Web Service, so a portfolio snapshot can be issued at the broker tier.
//
// The token is a read-only reporting credential the user generates inside their
// own IBKR account. It arrives in the request body, is used for these two calls
// and is then dropped: it is never written to the database, never logged, and
// never echoed back in the response. That is deliberate — storing it would make
// this app a target for something it has no need to hold, and IBKR tokens can
// be regenerated by the user in seconds.

const SEND_REQUEST_URL =
  "https://ndcdyn.interactivebrokers.com/AccountManagement/FlexWebService/SendRequest";

/** IBKR answers 1019 until the statement is built; it usually takes seconds. */
const MAX_ATTEMPTS = 5;
const RETRY_DELAY_MS = 1500;
/** Each leg of the handshake, so the function cannot hang on a stalled socket. */
const FETCH_TIMEOUT_MS = 15000;

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function fetchText(url: string): Promise<string> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
  try {
    const res = await fetch(url, {
      signal: controller.signal,
      headers: { "User-Agent": "TrimmTrack/1.0" },
    });
    if (!res.ok) throw new Error(`IBKR responded ${res.status}`);
    return await res.text();
  } finally {
    clearTimeout(timer);
  }
}

/** Error text for the client, with the token scrubbed in case it appears. */
function safeMessage(err: FlexError, token: string): string {
  return describeFlexError(err).split(token).join("<token>");
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  try {
    res.setHeader("Content-Type", "application/json");
    // The response embeds someone's holdings; no shared cache may keep it.
    res.setHeader("Cache-Control", "no-store");

    if (req.method !== "POST") {
      res.status(405).end(JSON.stringify({ error: "Method not allowed" }));
      return;
    }

    const rawHeader = req.headers["x-user-id"];
    const userIdRaw = Array.isArray(rawHeader) ? rawHeader[0] : rawHeader;
    const userId = userIdRaw?.trim();
    if (!userId || userId.length === 0 || userId.length > 128) {
      res.status(401).end(JSON.stringify({ error: "Missing x-user-id header" }));
      return;
    }

    const body = (req.body ?? {}) as { token?: unknown; queryId?: unknown };
    const token = typeof body.token === "string" ? body.token.trim() : "";
    const queryId = typeof body.queryId === "string" ? body.queryId.trim() : "";
    // Both are digit strings in IBKR's UI; validating the shape here keeps
    // anything odd out of a URL we are about to build.
    if (!/^\d{6,64}$/.test(token)) {
      res.status(400).end(JSON.stringify({ error: "Invalid Flex token" }));
      return;
    }
    if (!/^\d{3,32}$/.test(queryId)) {
      res.status(400).end(JSON.stringify({ error: "Invalid Flex query id" }));
      return;
    }

    const q = encodeURIComponent(queryId);
    const t = encodeURIComponent(token);

    // Step 1 — ask IBKR to build the statement.
    const sent = parseSendRequest(await fetchText(`${SEND_REQUEST_URL}?t=${t}&q=${q}&v=3`));
    if (!sent.ok) {
      res.status(502).end(
        JSON.stringify({ error: safeMessage(sent, token), code: sent.code }),
      );
      return;
    }

    // Step 2 — collect it, retrying only while IBKR says it is still building.
    let statement = parseStatement(
      await fetchText(`${sent.url}?t=${t}&q=${encodeURIComponent(sent.referenceCode)}&v=3`),
    );
    for (let attempt = 1; attempt < MAX_ATTEMPTS && !statement.ok && statement.retryable; attempt++) {
      await sleep(RETRY_DELAY_MS);
      statement = parseStatement(
        await fetchText(`${sent.url}?t=${t}&q=${encodeURIComponent(sent.referenceCode)}&v=3`),
      );
    }
    if (!statement.ok) {
      res.status(502).end(
        JSON.stringify({ error: safeMessage(statement, token), code: statement.code }),
      );
      return;
    }

    const positions = mergePositions(statement.positions).map((p) => ({
      ticker: toYahooTicker(p),
      symbol: p.symbol,
      description: p.description,
      currency: p.currency,
      assetCategory: p.assetCategory,
      quantity: p.quantity,
      markPrice: p.markPrice,
      value: p.positionValue,
      cost: p.costBasisMoney,
      unrealized: p.unrealizedPnl,
    }));

    res.status(200).end(
      JSON.stringify({
        // The account number identifies a real person's brokerage account, and
        // the caller has no use for it — only the last characters go back, so
        // the user can tell which account answered.
        account: statement.accountId ? `…${statement.accountId.slice(-4)}` : null,
        asOf: statement.toDate,
        positions,
      }),
    );
  } catch (e) {
    const err = e as Error;
    const message =
      err?.name === "AbortError" ? "IBKR did not respond in time" : (err?.message ?? "IBKR request failed");
    res.status(502).end(JSON.stringify({ error: message }));
  }
}
